/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package filmzadanie;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author R7
 */
public class GuiFrame extends javax.swing.JFrame {
 private final Film[] filmy;
    /**
     * Creates new form GuiFrame
     */
    public GuiFrame(Film[] filmy) {
        
        initComponents();
        this.filmy=filmy;
         
    for (int i = 0; i < filmy.length; i++) { //najdolezitejsia cast nacitanie z Objektu filmy ID cislo, podla ktoreho priraduje premenne
        ID_filmu_ComboBox.addItem(filmy[i].get_Film_ID_filmu());
         
         }
        //ostatok je iba manipulacia s objektom a get a set hodnot a nastavovania premenych swingu
    
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Je_pozicany_Label = new javax.swing.JLabel();
        Datum_posledneho_vratenia_Label = new javax.swing.JLabel();
        Datum_posledneho_pozicania_Label = new javax.swing.JLabel();
        Jednoduchy_popis_Label = new javax.swing.JLabel();
        Dlzka_trvania_Label = new javax.swing.JLabel();
        Nazov_filmu_Label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Funkcia_vratenia_Button = new javax.swing.JButton();
        Pocet_dni_pozicania_Label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Funkcia_pozicania_Button = new javax.swing.JButton();
        Da_sa_pozicat_Label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ID_filmu_ComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pozicovna_filmov");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Info_o_filme", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        Je_pozicany_Label.setText("Je_pozicany:");

        Datum_posledneho_vratenia_Label.setText("Datum_posledneho_vratenia:");

        Datum_posledneho_pozicania_Label.setText("Datum_posledneho_pozicania:");

        Jednoduchy_popis_Label.setText("Jednoduchy_popis:");

        Dlzka_trvania_Label.setText("Dlzka_trvania:");

        Nazov_filmu_Label.setText("Nazov_filmu:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Datum_posledneho_vratenia_Label)
                    .addComponent(Je_pozicany_Label)
                    .addComponent(Datum_posledneho_pozicania_Label)
                    .addComponent(Jednoduchy_popis_Label)
                    .addComponent(Dlzka_trvania_Label)
                    .addComponent(Nazov_filmu_Label))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Nazov_filmu_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Dlzka_trvania_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jednoduchy_popis_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Datum_posledneho_pozicania_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Datum_posledneho_vratenia_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Je_pozicany_Label))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Funkcia_vratenia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        Funkcia_vratenia_Button.setText("Funkcia vratenia");
        Funkcia_vratenia_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Funkcia_vratenia_ButtonActionPerformed(evt);
            }
        });

        Pocet_dni_pozicania_Label.setText("Pocet_dni_pozicania:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Funkcia_vratenia_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pocet_dni_pozicania_Label))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Funkcia_vratenia_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pocet_dni_pozicania_Label)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Funkcia pozicania", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        Funkcia_pozicania_Button.setText("Funkcia pozicania");
        Funkcia_pozicania_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Funkcia_pozicania_ButtonActionPerformed(evt);
            }
        });

        Da_sa_pozicat_Label.setText("Da_sa_pozicat:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Funkcia_pozicania_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Da_sa_pozicat_Label)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Funkcia_pozicania_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Da_sa_pozicat_Label)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vyber_ID_filmu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        // x=filmy[0].get_Film_ID_filmu();
        ID_filmu_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_filmu_ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ID_filmu_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ID_filmu_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_filmu_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_filmu_ComboBoxActionPerformed

       /* int xx=Integer.parseInt(ID_filmu_ComboBox.getSelectedItem().toString());
        ID_filmu_ComboBox.getSelectedIndex();
           for (int i = 0; i < filmy.length; i++) {
        ID_filmu_ComboBox.addItem(filmy[i].get_Film_ID_filmu());
         filmy[i].get_Film_ID_filmu();
        
         }*/
        
      
        Nazov_filmu_Label.setText("Nazov_filmu: "+filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Nazov_filmu());
        Dlzka_trvania_Label.setText("Dlzka_trvania: "+filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Dlzka_trvania());
        Jednoduchy_popis_Label.setText("Jednoduchy_popis_filmu: "+filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Jednoduchy_popis());
        if(!(filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Datum_posledneho_pozicania()==null))
        {
        Datum_posledneho_pozicania_Label.setText("Datum_posledneho_pozicania_filmu: "+Film.ft.format(filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Datum_posledneho_pozicania()));
        }
        else
        {
        Datum_posledneho_pozicania_Label.setText("Datum_posledneho_pozicania_filmu: null");    
        }
        
        Datum_posledneho_vratenia_Label.setText("Datum_posledneho_vratenia_filmu: "+Film.ft.format(filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Datum_posledneho_vratenia()));
        Je_pozicany_Label.setText("Je_pozicany_filmu: "+filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Je_pozicany());
        
        Da_sa_pozicat_Label.setText("Da_sa_pozicat: " +!(filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Je_pozicany()));
        Pocet_dni_pozicania_Label.setText("Pocet_dni_pozicania: ");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_filmu_ComboBoxActionPerformed

    private void Funkcia_pozicania_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Funkcia_pozicania_ButtonActionPerformed

        if(!filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Je_pozicany())
        {
        
        Da_sa_pozicat_Label.setText("Da_sa_pozicat: "+!filmy[ID_filmu_ComboBox.getSelectedIndex()].Funkcia_pozicania(new Date()));
        Je_pozicany_Label.setText("Je_pozicany_filmu: "+filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Je_pozicany());
        Datum_posledneho_pozicania_Label.setText("Datum_posledneho_pozicania_filmu: "+Film.ft.format(filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Datum_posledneho_pozicania()));
        }   
        else
        {
        //Da_sa_pozicat_Label.setText("Da_sa_pozicat: "+!filmy[ID_filmu_ComboBox.getSelectedIndex()].Funkcia_pozicania(new Date()));
    
        JOptionPane.showMessageDialog(new JFrame(),"ID_Filmu: "+filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_ID_filmu()+ " sa neda pozicat");      

        
        }    
        

        // TODO add your handling code here:
    }//GEN-LAST:event_Funkcia_pozicania_ButtonActionPerformed

    private void Funkcia_vratenia_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Funkcia_vratenia_ButtonActionPerformed
       // Da_sa_pozicat_Label.setText("Da_sa_pozicat: "+filmy[ID_filmu_ComboBox.getSelectedIndex()].Funkcia_pozicania(new Date()));
        if(filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Je_pozicany())
                
        {
          
        Pocet_dni_pozicania_Label.setText(String.valueOf(filmy[ID_filmu_ComboBox.getSelectedIndex()].Funkcia_vratenia(new Date())));
        Datum_posledneho_vratenia_Label.setText("Datum_posledneho_vratenia_filmu: "+Film.ft.format(filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Datum_posledneho_vratenia()));
        Da_sa_pozicat_Label.setText("Da_sa_pozicat: "+!filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Je_pozicany());
        Je_pozicany_Label.setText("Je_pozicany_filmu: "+filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_Je_pozicany());

        }
        else
        {
        JOptionPane.showMessageDialog(new JFrame(),"ID_Filmu: "+filmy[ID_filmu_ComboBox.getSelectedIndex()].get_Film_ID_filmu()+ " sa neda vratit");      
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_Funkcia_vratenia_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new GuiFrame().setVisible(true);
                 
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Da_sa_pozicat_Label;
    private javax.swing.JLabel Datum_posledneho_pozicania_Label;
    private javax.swing.JLabel Datum_posledneho_vratenia_Label;
    private javax.swing.JLabel Dlzka_trvania_Label;
    private javax.swing.JButton Funkcia_pozicania_Button;
    private javax.swing.JButton Funkcia_vratenia_Button;
    private javax.swing.JComboBox ID_filmu_ComboBox;
    private javax.swing.JLabel Je_pozicany_Label;
    private javax.swing.JLabel Jednoduchy_popis_Label;
    private javax.swing.JLabel Nazov_filmu_Label;
    private javax.swing.JLabel Pocet_dni_pozicania_Label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
